---
- hosts: app
  vars_files:
    - vars.yml
    - private/private-vars.yml

  sudo: yes
  user: root

  tasks:
    - name: update repo
      git: repo={{project_repo}} version=master dest={{project_root}}
      sudo: yes
      sudo_user: web
      notify:
        - update config
        - reload {{project_name}}
        - flush iptables

  handlers:
    - name: update config
      copy: src=../config-production.js dest={{project_root}}/config-production.js owner=web group=web mode=755

    - name: reload {{project_name}}
      service: name={{project_name}} state=reloaded

    - name: flush iptables
      shell: iptables -F
