---
- hosts: 127.0.0.1

  tasks:
    - name: make sure our less is compiled
      local_action: command chdir=../ gulp build-assets

- hosts: app
  vars_files:
    - vars.yml
    - private/private-vars.yml

  sudo: yes
  user: root

  tasks:

    - name: update repo
      git: repo={{project_repo}} version=master dest={{project_root}}
      sudo: yes
      sudo_user: web

    - name: copy over assets
      copy: src=../static-dist dest={{project_root}}/static-dist owner=web group=web mode=755

    - name: update config
      template: src=templates/config.js.j2 dest={{project_root}}/config-production.js backup=yes
      sudo: yes
      sudo_user: web
      notify:
        - reload {{project_name}}
        - flush iptables

  handlers:
    - name: reload {{project_name}}
      service: name={{project_name}} state=reloaded

    - name: flush iptables
      shell: iptables -F
