---
- hosts: app
  vars_files:
    - vars.yml
    - private/private-vars.yml

  sudo: yes
  user: root

  tasks:

    - name: make sure our less is compiled
      local_action: chdir=../ npm run less

    - name: update repo
      git: repo={{project_repo}} version=master dest={{project_root}}
      sudo: yes
      sudo_user: web

    - name: copy over generated css
      copy: src=../static/{{theme_to_deploy}}/css/style.css dest={{project_root}}/static/{{theme_to_deploy}}/css/style.css owner=web group=web mode=755

    - name: update config
      copy: src=../config-production.js dest={{project_root}}/config-production.js owner=web group=web mode=755
      notify:
        - reload {{project_name}}
        - flush iptables

  handlers:
    - name: reload {{project_name}}
      service: name={{project_name}} state=reloaded

    - name: flush iptables
      shell: iptables -F
