---

- name: install couchdb
  hosts: vagrantgroup
  sudo: yes
  user: root

  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes

  roles:
    - {role: ANXS.build-essential}
    - {role: ANXS.erlang, erlang_version: 17.1}
    - {role: guillaumededrie.couchdb, couchdb_version: 1.6.1}
