---
- hosts: vagrantgroup
  vars_files:
    - vars.yml

  sudo: yes
  user: root

  tasks:
    - name: create couchdb user
      command: chdir={{project_root}} ./create-admin-user.sh

    - name: npm install all the things
      command: chdir={{project_root}} make unit

    - name: bootstrap database
      command: chdir={{project_root}} npm run bootstrap
      notify:
        - reload {{project_name}}
        - flush iptables

  handlers:
    - name: reload {{project_name}}
      service: name={{project_name}} state=reloaded

    - name: flush iptables
      shell: iptables -F
