---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - private/private-vars.yml

  tasks:
    - name: push views
      command: chdir=../ couchapp push couch-data/views.js https://{{db_user}}:{{db_password}}@{{db_host}}/{{db_name}}
